<a href="https://colab.research.google.com/github/sinara08/Campusx/blob/main/Python_Fundamentals/Daily_Sessions/session_13_numpy_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

In [ ]:
c = []
for i in range(len(a)):
    c.append(a[i]*b[i])

In [ ]:
for (i = 0; i < rows; i++) {
  c[i] = a[i]*b[i];
}

In [ ]:
for (i = 0; i < rows; i++) {
  for (j = 0; j < columns; j++) {
    c[i][j] = a[i][j]*b[i][j];
  }
}

In [ ]:
c = a * b

### Creating Numpy Arrays

In [3]:
# np.array
import numpy as np
a = np.array([1,2,3]) #vector
print(a, type(a))

[1 2 3] <class 'numpy.ndarray'>


In [5]:
# 2D and 3D

b = np.array([[1,2,3],[4,5,6]]) #matrix
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
c=[[[1,2,3],[4,5,6],[7,8,8]]] #tensor
print(c)

[[[1, 2, 3], [4, 5, 6], [7, 8, 8]]]


In [8]:
# dtype
np.array([1,2,3],dtype = float)

array([1., 2., 3.])

In [9]:
# np.arange
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [11]:
# with reshape
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [13]:
# np.ones and np.zeros
np.ones((3,4)) #use - to initialize weights in neural network

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
# np.random
np.random.random((6,2))

array([[0.82115828, 0.8952349 ],
       [0.85043892, 0.06921323],
       [0.63270544, 0.96754653],
       [0.7615068 , 0.72797651],
       [0.9044062 , 0.69998777],
       [0.98247304, 0.94779759]])

In [16]:
# np.linspace - linearly spaced, for a given range points are generated in equal distance.
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [17]:
# np.identity
np.identity(3) #diagonal item will be 1 and rest will be 0 in numpy array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [18]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1, a2, a3)

[0 1 2 3 4 5 6 7 8 9] [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]] [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [21]:
# ndim #to give dimension of given array
print(a1.ndim, a2.ndim, a3.ndim)

1 2 3


In [22]:
# shape
#3d - first number - how many 2 d array , next 2 numbers indicate shape of 2d array
print(a1.shape, a2.shape, a3.shape)

(10,) (3, 4) (2, 2, 2)


In [23]:
# size
print(a1.size, a2.size, a3.size)

10 12 8


In [24]:
# itemsize - how much mem will be used for each items
print(a1.itemsize, a2.itemsize, a3.itemsize)

8 8 8


In [26]:
# dtype - type of np array
print(a1.dtype, a2.dtype, a3.dtype)

int64 float64 int64


### Changing Datatype

In [33]:
# astype
print(a3,'\n', a3.dtype,'\n', a3.astype(np.int32).dtype)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] 
 int64 
 int32


### Array Operations

In [35]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1,'\n a2 -',a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 
 a2 - [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [37]:
# scalar operations

# arithmetic
a1 ** 2 # a1- matrix, 2 - scalar

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [39]:
# relational
a2 > 15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [40]:
# vector operations - between 2 numpy arrays
# arithmetic - for all operators

a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

### Array Functions

In [41]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[17., 77., 71.],
       [46., 69., 91.],
       [49., 42., 71.]])

In [47]:
# max/min/sum/prod
#0 - column
#1 - row
print(np.max(a1, axis=0))
print(np.min(a1, axis=1))
print(np.prod(a1))
print(np.sum(a1, axis = 0))

[49. 77. 91.]
[17. 46. 42.]
3922383281684868.0
[112. 188. 233.]


In [ ]:
# mean/median/std/var

In [ ]:
# trigonomoetric functions

In [ ]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

In [ ]:
# log and exponents

In [ ]:
# round/floor/ceil

### Indexing and Slicing

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

### Iterating

### Reshaping

In [ ]:
# reshape

In [ ]:
# Transpose

In [ ]:
# ravel

### Stacking

In [ ]:
# horizontal stacking

In [ ]:
# Vertical stacking

### Splitting

In [ ]:
# horizontal splitting

In [ ]:
# vertical splitting